# Ques 1. Create a null vector of size 10 but the fifth value which is 1.

In [2]:
import numpy as np
a=np.zeros(10,dtype=int)
a[4]=1
print(a)

[0 0 0 0 1 0 0 0 0 0]


# Ques 2. Create a vector with values ranging from 10 to 49.

In [3]:
b=np.arange(10,49)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


# Ques 3. Create a 3x3 matrix with values ranging from 0 to 8

In [5]:
c = np.arange(9).reshape(3,3)
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
# Alternate
d=np.random.randint(0,9,(3,3))
print(d)

[[0 8 7]
 [5 4 4]
 [4 1 4]]


# Ques 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [21]:
s=np.array([1,2,0,0,4,0])
print("Original array is: ",s)
non_zero=np.nonzero(s)
print("Indices of non-zero elements are: ",non_zero)

Original array is:  [1 2 0 0 4 0]
Indices of non-zero elements are:  (array([0, 1, 4], dtype=int64),)


# Ques 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [11]:
b = np.random.rand(10,10)
print("Original Array : \n", b)
bmin, bmax = b.min(), b.max()
print("\n Minimum Value : " ,bmin,)
print("\n Maximum Value : " ,bmax,)

Original Array : 
 [[5.41739643e-01 6.38585306e-01 6.43505056e-01 9.45298457e-01
  6.49059289e-01 8.59126603e-01 8.90045503e-01 3.17011474e-02
  6.83166940e-01 2.45523732e-01]
 [4.62058069e-01 2.25919636e-01 8.25157674e-01 4.94719458e-01
  9.06765239e-01 9.93235073e-01 5.11901930e-01 4.63921876e-01
  2.17005401e-01 3.77676469e-01]
 [9.77271567e-01 9.58503626e-01 7.93791492e-01 5.22603941e-01
  2.97502626e-01 3.86820011e-01 1.49666599e-01 3.06238336e-01
  5.74075005e-01 2.93018268e-01]
 [7.24819110e-01 5.64296164e-01 1.17708810e-01 7.66019976e-01
  9.87921579e-01 5.93833725e-01 9.84697006e-01 5.60866747e-04
  6.64125726e-01 1.48383798e-01]
 [1.59633670e-01 9.48567751e-02 2.47247695e-01 1.79433555e-01
  3.16674948e-02 8.72648384e-01 1.99188920e-01 5.07551035e-01
  8.63042761e-01 2.12507671e-01]
 [2.10041595e-01 4.72680075e-01 3.44462516e-01 8.99567714e-03
  9.33827978e-01 3.87423699e-01 9.26039986e-01 4.37593244e-01
  9.95996425e-01 3.76364034e-01]
 [3.68973485e-01 9.66432145e-01 6.33711

# Ques 6. Create a random vector of size 30 and find the mean value.

In [12]:
c = np.random.rand(30)
print("Original array : \n", c)
print("Mean Value : \n", np.mean(c))


Original array : 
 [0.30259776 0.35100743 0.77378226 0.70410538 0.54385931 0.68005605
 0.98350554 0.83141045 0.46063805 0.98009951 0.3335592  0.3252936
 0.68316048 0.81681069 0.23614576 0.92161411 0.51369054 0.32230181
 0.25497105 0.43054107 0.57074059 0.56796591 0.91231598 0.01870782
 0.71827685 0.85493042 0.96563326 0.92323923 0.09737467 0.66604438]
Mean Value : 
 0.5914793047711259
